version: '3'


services:
  restapi:
    build: ./restapi
    container_name: restapi
    ports:
      - "8000:8000"
    volumes:
      - ./restapi:/home/restapi
      - ./restapi/run.sh:/usr/local/bin/run.sh
    command : bash -c "run.sh"
      # - run.sh
